[Configuracion_Rutas]
# Ruta al archivo de texto que contiene el ID numerico de la lista
PATH_ID_LISTA=C:\FORMS\idlista.txt

# Ruta a la carpeta de proceso (donde se cuentan archivos .jpg y .jpeg)
PATH_PROCESO=C:\FORMS\len2026

# Ruta a la carpeta de transferencia (donde se cuentan todos los archivos)
PATH_TRANSFER=C:\FORMS\transfer

[Configuracion_Equipo]
# Nombre identificador unico para este equipo en la base de datos
NOMBRE_EQUIPO=forms_ingles(parciales)

# Ruta absoluta al ejecutable psql.exe de PostgreSQL
PATH_PSQL=C:\Program Files\PostgreSQL\17\bin\psql.exe

[Configuracion_BaseDatos]
# Direccion IP o Host del servidor de base de datos
DB_HOST=10.211.128.151

# Nombre de la base de datos
DB_NAME=sudcra

# Puerto de conexion (por defecto 5432)
DB_PORT=5432

# Usuario de la base de datos
DB_USER=postgres

# Contrasena del usuario
DB_PASS=fec4a5n5
