[Configuracion_Rutas]
# Ruta al archivo de texto de OneDrive que contiene el ID de Sharepoint
# El formato esperado es: string(triggerBody()?['358']) 4.Save
PATH_TXT_ORAL=C:\Users\evaluacionestransver\OneDrive - Fundacion Instituto Profesional Duoc UC\sudcra-repositorio\idlista_imagenes\idlista.txt

# Ruta al archivo de texto que contiene la cantidad de tickets pendientes
# El formato esperado es: string(outputs('0'))
PATH_TICKETS=C:\Users\evaluacionestransver\OneDrive - Fundacion Instituto Profesional Duoc UC\sudcra-repositorio\idlista_imagenes\pendientes.txt

[Configuracion_Equipo]
# Nombre identificador para el registro de Sharepoint (Por defecto: sudcra)
NOMBRE_EQUIPO=sudcra

# Ruta absoluta al ejecutable psql.exe de PostgreSQL
PATH_PSQL=C:\Program Files\PostgreSQL\17\bin\psql.exe

[Configuracion_BaseDatos]
DB_HOST=10.211.128.151
DB_NAME=sudcra
DB_PORT=5432
DB_USER=postgres
DB_PASS=fec4a5n5

[Configuracion_Pulso]
# Intervalo de ejecucion (PT1H = cada 1 hora, PT5M = cada 5 minutos)
INTERVALO=PT1H
NOMBRE_PULSO=pulso_sharepoint
