-- ************** Creación de la tabla RECAUDACION_BONOS_MEDICOS **************
CREATE TABLE RECAUDACION_BONOS_MEDICOS (
    RUT_MEDICO VARCHAR2(10) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(50) NOT NULL,
    TOTAL_RECAUDADO NUMBER(10) NOT NULL,
    UNIDAD_MEDICA VARCHAR2(40) NOT NULL
);

-- ************** Consulta para calcular la recaudación total y poblar la tabla **************
INSERT INTO RECAUDACION_BONOS_MEDICOS (RUT_MEDICO, NOMBRE_COMPLETO, TOTAL_RECAUDADO, UNIDAD_MEDICA)
SELECT 
    TO_CHAR(M.RUT_MED) || '-' || M.DV_RUN AS RUT_MEDICO,
    M.PNOMBRE || ' ' || M.APATERNO || ' ' || M.AMATERNO AS NOMBRE_COMPLETO,
    SUM(BC.COSTO) AS TOTAL_RECAUDADO,
    UC.NOMBRE AS UNIDAD_MEDICA
FROM 
    BONO_CONSULTA BC
INNER JOIN 
    MEDICO M ON BC.RUT_MED = M.RUT_MED
INNER JOIN 
    UNIDAD_CONSULTA UC ON M.UNI_ID = UC.UNI_ID
LEFT JOIN 
    CARGO C ON M.CAR_ID = C.CAR_ID
WHERE 
    M.CAR_ID NOT IN (100, 500, 600) -- Excluímos los cargos indicados
    AND EXTRACT(YEAR FROM BC.FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE) - 1 -- Año anterior
GROUP BY 
    TO_CHAR(M.RUT_MED) || '-' || M.DV_RUN,
    M.PNOMBRE,
    M.APATERNO,
    M.AMATERNO,
    UC.NOMBRE
ORDER BY 
    TOTAL_RECAUDADO ASC; -- Ordenamos
