-- ************** Creación de la tabla DETALLE_PERDIDAS_BONOS **************
CREATE TABLE DETALLE_PERDIDAS_BONOS (
    ESPECIALIDAD_MEDICA VARCHAR2(40) NOT NULL,
    CANTIDAD_BONOS NUMBER(10) NOT NULL,
    MONTO_PERDIDA NUMBER(10) NOT NULL,
    FECHA_BONO_ANTIGUO DATE NOT NULL,
    ESTADO_DE_COBRO VARCHAR2(20) NOT NULL
);
-- ************** Consulta para poblar la tabla con los datos respectivos **************
INSERT INTO DETALLE_PERDIDAS_BONOS (ESPECIALIDAD_MEDICA, CANTIDAD_BONOS, MONTO_PERDIDA, FECHA_BONO_ANTIGUO, ESTADO_DE_COBRO)
SELECT 
    EM.NOMBRE AS ESPECIALIDAD_MEDICA,
    COUNT(BC.ID_BONO) AS CANTIDAD_BONOS,
    SUM(BC.COSTO) AS MONTO_PERDIDA,
    MIN(BC.FECHA_BONO) AS FECHA_BONO_ANTIGUO,
    CASE 
        WHEN EXTRACT(YEAR FROM BC.FECHA_BONO) >= EXTRACT(YEAR FROM SYSDATE) - 1 THEN 'COBRABLE'
        ELSE 'INCOBRABLE'
    END AS ESTADO_DE_COBRO
FROM 
    BONO_CONSULTA BC
INNER JOIN 
    ESPECIALIDAD_MEDICA EM ON BC.ESP_ID = EM.ESP_ID
WHERE 
    BC.ID_BONO NOT IN (SELECT P.ID_BONO FROM PAGOS P) -- Condicion para bonos no pagados
GROUP BY 
    EM.NOMBRE,
    CASE 
        WHEN EXTRACT(YEAR FROM BC.FECHA_BONO) >= EXTRACT(YEAR FROM SYSDATE) - 1 THEN 'COBRABLE'
        ELSE 'INCOBRABLE'
    END
ORDER BY 
    CANTIDAD_BONOS DESC, -- Ordenamos de mayor a menor respecto de cantidad de bonos
    MONTO_PERDIDA DESC;  -- En caso de empate se ordena de mayor a menor respecto de monto perdida
