# Configuración sincronización nube
# LOCAL
DB_HOST=10.211.128.151
DB_NAME=sudcra
DB_USER=postgres
DB_PASS=fec4a5n5
DB_PORT=5432

# CLOUD (Neon)
CLOUD_URL=postgresql://neondb_owner:npg_zfDn3gWRsb0K@ep-dry-surf-anz599a8-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
CLOUD_PASS=npg_zfDn3gWRsb0K
CLOUD_USER=neondb_owner
CLOUD_HOST=ep-dry-surf-anz599a8-pooler.c-6.us-east-1.aws.neon.tech
CLOUD_DB=neondb

# PSQL PATH
PATH_PSQL=C:\Program Files\PostgreSQL\16\bin\psql.exe
